name: Deploy Infraestructura AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Inicializar Terraform
        run: terraform init

      - name: Planificar infraestructura
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          terraform plan -out=tfplan \
            -var="aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" \
            -var="aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
            -var="aws_region=${{ secrets.AWS_REGION }}" \
            -var="github_token=${{ secrets.GH_TOKEN }}"

      - name: Aplicar infraestructura
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: terraform apply -auto-approve tfplan
        
      - name: Obtener y mostrar IP pública
        id: ip
        run: echo "ip=$(terraform output -raw public_ip)" >> $GITHUB_OUTPUT

      - name: Imprimir IP pública
        run: echo "La IP pública de EC2 es ${{ steps.ip.outputs.ip }}"
